version: "3.9"

services:
  redis:
    image: redis:alpine
    restart: always
    container_name: session_storage
  db:
    image: postgres:16-bullseye
    restart: always
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
  server:
    build: ./server
    restart: always
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: bash -c "python3 src/run.py"