# Server address
HOST = '127.0.0.1'
PORT = 8000

# Server router prefixes
API_PREFIX = '/api'
MEDIA_PREFIX = '/media'
AUTH_ROUTER_PREFIX = '/auth'
UNITS_ROUTER_PREFIX = '/units'
MODULES_ROUTER_PREFIX = '/modules'
HOBBIES_ROUTER_PREFIX = '/hobbies'
API_VERSION_1_PREFIX = API_PREFIX + '/v1'
WALKTHROUGHES_ROUTER_PREFIX = '/walkthroughes'

# Server URLs
ME_URL = '/me'
SIGN_UP_URL = '/sign-up'
SIGN_IN_URL = '/sign-in'
SIGN_OUT_URL = '/sign-out'

# Client URLs
SERVER_URL = f'http://{HOST}:{PORT}'
MEDIA_URL = f'{SERVER_URL}{MEDIA_PREFIX}'
API_V1_URL = f'{SERVER_URL}{API_VERSION_1_PREFIX}'
AUTH_URL = f'{API_V1_URL}{AUTH_ROUTER_PREFIX}'
SIGN_UP_FULL_URL = f'{AUTH_URL}{SIGN_UP_URL}'
SIGN_IN_FULL_URL = f'{AUTH_URL}{SIGN_IN_URL}'
SIGN_OUT_FULL_URL = f'{AUTH_URL}{SIGN_OUT_URL}'
ME_FULL_URL = f'{AUTH_URL}{ME_URL}'
HOBBIES_URL = f'{API_V1_URL}{HOBBIES_ROUTER_PREFIX}'
MODULES_URL = f'{API_V1_URL}{MODULES_ROUTER_PREFIX}'
UNITS_URL = f'{API_V1_URL}{UNITS_ROUTER_PREFIX}'
WALKTHROUGHES_URL = f'{API_V1_URL}{WALKTHROUGHES_ROUTER_PREFIX}'
